### ISSUE TITLE
Doesn't work ... Please update code?

### ISSUE THREAD

**Issue by rlam3** [rollbar/rollbar-flask-example#2]
Doesn't work ... Please update code? 
However if I added:
rollbar.report_message('Got an IOError in the main loop', 'warning')
it works and i see the first error.

**Comment by bxsx** [comment]
Hi @rlam3,

I'm sorry for a late response. Do you still experience any issues with the example?
If so, we have just updated the example, so you may give it a try! :)

As this is very old issue, I'm closing it for now but please don't hesitate to (re)open it for further investigation.
Thanks!
