### ISSUE TITLE
Python 3 example?

### ISSUE THREAD

**Issue by scarroll32** [rollbar/rollbar-flask-example#4]
This is a very useful repo but a Python 3 upgrade might be a good idea. Should be fairly close to what it is like now, at least change the text in the README.

**Comment by ArturMoczulski** [comment]
Thanks @seanfcarroll . I'll look into this

**Comment by bxsx** [comment]
Hi @seanfcarroll and thanks for you contribution!

I have just merged a PR #5 with a support for Python3.

I'm closing this issue for now but please let us know if you have any other concerns or ideas!
